name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: f5d9de8bfc08cc97feb75fc0b15f3308274a6a69

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 80
      containerPort: 3000

ingress:
  - name: linktree.flowception.co.uk
    selector: flowception-linktree
    path: /
    port: 3000
    host: linktree.flowception.co.uk