name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: 9d1caa77437230e69a8d76b4d2209e39e19bb604

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 80
      containerPort: 3000

ingress:
  - name: linktree.flowception.co.uk
    selector: flowception-linktree
    path: /
    port: 3000
    host: linktree.flowception.co.uk