name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: 6da9498e32a4bf2d4cc0f6f4be755838209b583e

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

ingress:
  - name: linktree.flowception.co.uk
    selector: flowception-linktree
    path: /
    port: 3000
    host: linktree.flowception.co.uk


service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 80
      containerPort: 3000
