name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: 1a46bc582bcc06615bd9699a0162ab2591aefe95

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

ingress:
  - name: linktree.flowception.co.uk
    selector: flowception-linktree
    path: /.*
    port: 80
    host: linktree.flowception.co.uk


service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 3000
