name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: 17353770b2552690726f4be0b78da66699ff179b

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

ingress:
  - name: linktree.flowception.com
    selector: flowception-linktree
    path: /.*
    port: 80
    host: linktree.flowception.com


service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 3000
