name: flowception-linktree

namespace: flowception
env:
  APP_VERSION: 9db5d0fa3e2b12104790279d84e367607a8bfa71

deployment:
  - name: flowception-linktree
    image: invisibug/flowception-linktree

service:
  loadBalancer:
    - name: flowception-linktree
      selector: flowception-linktree
      port: 80
      containerPort: 3000

ingress:
  - name: linktree.flowception.co.uk
    selector: flowception-linktree
    path: /
    port: 3000
    host: linktree.flowception.co.uk